### ISSUE TITLE
Usernames kht-

### ISSUE THREAD

**Issue by matejtarca** [kosice-hack-token/KHT-rest_api#2]
As we moved from using kht as our main brand it doesn't make sense that usernames still need to start with kht. I think that we should give users freedom to chose whatever username they want. Maybe only when creating account on blockchain we can use that prefix and then make sure to always include it when making requests to blockchain. Feel free to comment.

**Comment by GLise710** [comment]
Doesn't matter to me. It is just a minimal change in the code. I'm fine with changing it as we still have not released the project and we have no users it would affect in any way.
